// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/**
 * @title ISP1Verifier
 * @author Succinct Labs
 * @notice Interface for the SP1 zkVM Verifier
 * @dev Based on Succinct Labs SP1 verifier contracts v4.0.0-rc.3
 * @custom:address-sepolia 0x3B6041173B80E77f038f3F2C0f9744f04837185e (Ethereum Sepolia)
 * @custom:address-mantle-sepolia Deploy your own SP1Verifier for Mantle
 */
interface ISP1Verifier {
    /**
     * @notice Thrown when the verifier selector from the proof does not match
     * @param received The verifier selector from the first 4 bytes of the proof
     * @param expected The verifier selector from the first 4 bytes of VERIFIER_HASH
     */
    error WrongVerifierSelector(bytes4 received, bytes4 expected);

    /**
     * @notice Thrown when the proof verification fails
     */
    error InvalidProof();

    /**
     * @notice Verifies a proof generated by SP1 zkVM
     * @dev It is expected that the first 4 bytes of proofBytes match the first 4 bytes
     *      of the target verifier's VERIFIER_HASH
     * @param programVKey The verification key for the RISC-V program
     * @param publicValues The public inputs/outputs encoded as bytes
     * @param proofBytes The proof of program execution from SP1 zkVM
     */
    function verifyProof(
        bytes32 programVKey,
        bytes calldata publicValues,
        bytes calldata proofBytes
    ) external view;
}

/**
 * @title ISP1VerifierWithHash
 * @author Succinct Labs
 * @notice Extended SP1 Verifier interface with verifier hash identification
 */
interface ISP1VerifierWithHash is ISP1Verifier {
    /**
     * @notice Returns the hash of the verifier for proof compatibility checking
     * @return The 32-byte hash identifying this verifier version
     */
    function VERIFIER_HASH() external pure returns (bytes32);

    /**
     * @notice Returns the version string of the verifier
     * @return The version string (e.g., "v4.0.0-rc.3")
     */
    function VERSION() external pure returns (string memory);

    /**
     * @notice Hashes public values to a field element inside Bn254
     * @param publicValues The public values to hash
     * @return The hashed value constrained to Bn254 field
     */
    function hashPublicValues(bytes calldata publicValues) external pure returns (bytes32);
}
